name: puzzles
description: puzzles for everyone
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.3
  bloc: ^8.1.1
  drift: ^2.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4
  intl: ^0.17.0
  json_annotation: ^4.8.0
  local_storage_puzzles_api:
    path: ./packages/local_storage_puzzles_api
  puzzles_api:
    path: ./packages/puzzles_api
  puzzles_repository:
    path: ./packages/puzzles_repository
  words_generator_repository:
    path: packages/words_generator_repository

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.1
  build_runner: ^2.2.0
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/svgs/
