name: puzzles_api
description: The interface and models for an API providing access to puzzles saved locally.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  meta: ^1.8.0
