name: local_storage_puzzles_api
description: A Flutter implementation of the Puzzles  that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.0

dependencies:
  drift: ^2.6.0

  flutter:
    sdk: flutter
  get_it: ^7.2.0
  meta: ^1.8.0
  mockito: ^5.4.0
  path: ^1.8.2
  path_provider: ^2.0.14
  puzzles_api:
    path: ../puzzles_api

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  sqflite_common_ffi: ^2.2.2
  test: ^1.22.0
  very_good_analysis: ^3.1.0
