name: puzzles_repository
description: A repository that handles puzzles  related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  local_storage_puzzles_api:
    path: ../local_storage_puzzles_api
  puzzles_api:
    path: ../puzzles_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
